Exercise semantic html by Raul Valencia
DkSanjed/html-tutorial pull request #2
Opened 2020-04-22 03:32 UTC by DkSanjed

Created semantic html

2020-04-22 20:33 UTC, juancho11gm commented on 3-semantic-html/semantic.html
> +            <h3>Raúl Valencia</h3>
Where is the `<h2>` ?. If you prefer you can change the `<h3>` to `<h2>`. It depends on the headers that you will have on the web page

2020-04-22 20:36 UTC, juancho11gm commented on 3-semantic-html/semantic.html
> +                    <h1>This is the main</h1>
It's better to have only one `<h1>` per page.

2020-04-22 20:37 UTC, juancho11gm requested changes
Good job! I see that you understand the concept. Please see the comments and send the changes.

2020-04-23 16:47 UTC, juancho11gm commented on 3-semantic-html/semantic.html
> +                        <br>
Using <br> it's a bad practice because it's not a semantic tag. We are going to see how to put a line break with CSS.

2020-04-29 01:44 UTC, pushdev-code approved these changes

2020-04-29 01:44 UTC, merged